version: "3.9" 
services:
  web3:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume03:/var/log
    links:
      - redis
  redis3:
    image: redis
volumes:
  logvolume03: {}
