/***
 CREATOR RIZXYU(SXZY)
 github.com/Rizxyu
 Dont delete credit nigga
***/
let handler = async (m, { conn, usedPrefix, text, command}) => {

var user = global.db.data.users[m.sender]

global.waifu = ["rem", "asuna", "mikasa", "saber", "kagome", "taiga", "holo","rin","megumin","yuno","kyouko","emilia","chitoge","tohru","zerotwo","rias","sakura","yui","ayase","erza","mio","rukia","albedo","alice","siesta","origami","elaina","ninymralei","aqua","bocchi","makise","nami","ayase""mai", "nanami",
    "yukino",
    "chizuru",
    "kaori",
    "mitsuki",
    "hinata",
    "yotsuba",
    "miku",
    "itsuki",
    "haru",
    "ichika",
    "nino",
    "mio",
    "ritsu",
    "mugi",
    "azusa",
    "yui",
    "nagisa",
    "usagi",
    "chibiusa",
    "amane",
    "nagisa",
    "yukine",
    "kohaku",
    "nero",
    "tamamo",
    "artoria",
    "scathach",
    "jeanne",
    "okita",
    "rider",
    "sakura",
    "tamamo",
    "illya",
    "jeanne",
    "chloe",
    "yui",
    "yukino",
    "yui",
    "ayase",
    "akane",
    "moka",
    "shiro",
    "jibril",
    "raphael",
    "raphaelle",
    "tanya",
    "megumin",
    "aqua",
    "yukino",
    "yui",
    "natsuki",
    "sayori",
    "yuri",
    "monika",
    "hinata",
    "yui",
    "nobara",
    "maki",
    "megumi",
    "saki",
    "miki",
    "anju",
    "aya",
    "misa",
    "umi",
    "riko",
    "hanamaru",
    "yoshiko",
    "mari",
    "riko",
    "yuki",
    "saya",
    "kuro",
    "ayame",
    "botan",
    "sui",
    "fubuki",
    "mio",
    "sora",
    "kaho",
    "minase",
    "yuuki",
    "kou",
    "kaede",
    "rin",
    "shirogane",
    "kaguya",
    "hayasaka",
    "miko",
    "nagatoro",
    "rio",
    "shamiko",
    "coco",
    "tsugumi",
    "maki",
    "ruka",
    "kazuya",
    "chihiro",
    "roxy",
    "sylphy",
    "kukuru",
    "kotori",
    "yoh",
    "asuka",
    "mana",
    "izumi",
    "hajime",
    "yuri",
    "yulia",
    "iris",
    "princess",
    "serval",
    "carole",
    "tuesday",
    "chise",
    "riya",
    "mei",
    "madoka",
    "homura",
    "sayaka",
    "kyoko",
    "mami",
    "nagisa",
    "alice",
    "akame",
    "esdeath",
    "leone",
    "kurome",
    "mine",
    "seryu",
    "mari",
    "non",
    "yuuna",
    "chiyo",
    "sakurajima",
    "kaede",
    "tomoe",
    "mai",
    "shoko",
    "tamaki",
    "sakuta",
    "nino",
    "ichika",
    "miku",
    "yotsuba",
    "itsuki",
    "riku",
    "yozora",
    "senri",
    "tokiko",
    "kohaku",
    "kusunoki",
    "tomoe",
    "kurumi",
    "yuki",
    "nanami",
    "komachi",
    "yotsugi",
    "kiss-shot",
    "shinobu",
    "senjougahara",
    "hana",
    "medaka",
    "zakuro",
    "pepperoni",
    "sheep",
    "vanilla",
    "chocola",
    "azuki",
    "cinnamon",
    "maple",
    "kafuu",
    "papi",
    "centorea",
    "meroune",
    "suu",
    "rachnera",
    "miia",
    "yuno",
    "mikaela",
    "mikasa",
    "nanoha",
    "fate",
    "hayate",
    "vivio",
    "miyuki",
    "tatsuya",
    "kazuya",
    "chizuru",
    "mami",
    "sayaka",
    "homura",
    "kyoko",
    "kallen",
    "cc",
    "cornelia",
    "euphemia",
    "nunnally",
    "shirley",
    "hime",
    "tokiko",
    "aya",
    "alice",
    "hikari",
    "mirai",
    "yayoi",
    "miki",
    "inori",
    "hime",
    "chitose",
    "mana",
    "yuuna",
    "kohane",
    "kaguya",
    "cure",
    "miki",
    "kari",
    "naomi",
    "futaba",
    "yui",
    "eriri",
    "utaha",
    "megumi",
    "kato",
    "akane",
    "inori",
    "mary",
    "ryuko",
    "satsuki",
    "mako",
    "nonon",
    "nui",
    "san",
    "mitsuki",
    "ichigo",
    "zero",
    "kokoro",
    "hikari",
    "ichika",
    "kaito",
    "rina",
    "mea",
    "yami",
    "lala",
    "momo",
    "nana",
    "yoruka",
    "renge",
    "yuruyuri",
    "hinata",
    "homura",
    "kuroyukihime",
    "kyouko",
    "saya",
    "aya",
    "alice",
    "yuri"]

var bintang = {
"satu": "⭐",
"dua": "⭐⭐",
"tiga": "⭐⭐⭐",
"empat": "⭐⭐⭐⭐",
"lima": "⭐⭐⭐⭐⭐",
"enam": "⭐⭐⭐⭐⭐⭐"
}//star how good is the waifu
   
   let waif = text.trim().toLowerCase() // to filter text
     
   if (!waifu.includes(waif)) throw `*Pilih Waifu Apa Yg Kamu Inginkan:\n\n${waifu.map(waif => `› ${waif}`).join('\n')}

     Cara Menggunakan:
     *${usedPrefix + command} <namewaifu>*
     
     Contoh:
     *${usedPrefix + command} rem*
     `

    if (user.waifu == "") {
    user.waifu = waif
    m.reply(`*Anda Telah Memilih Waifu ${waif}*`)
    } else if (user.waifu) {
    m.reply(`*Anda Sudah Punya Waifu ${user.waifu} Tidak Bisa Diganti*`)
   }

}

handler.help = ['selectwaifu <type>']
handler.tags = ['rpg']
handler.command = /^(slectwaifu|selectwaifu)$/i
handler.limit = 1
handler.register = false
export default handler
